
spring:
  datasource:
    url: jdbc:mariadb://192.168.99.100/companyhub?createDatabaseIfNotExist=true&useMysqlMetadata=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver