version: 1
update_configs:  
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - "github-actions"
    default_assignees:
      - "paulushcgcj"
    default_labels:
      - "security"
      - "bug"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true