name: Branching Name Convention

on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z]+)\/([RTA\-|maven]+[\d|\/]+.*)' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'feature,issue,fix,dependabot' # All branches should start with the given prefix
          ignore: master,develop # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 255 # Max length of the branch name
