name: First User Interaction Greeting

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Welcome to my Road to Architect, thanks for your collaboration by oppening this issue'
          pr-message: 'Thank you for your first pull request'
