name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pre-flight:
    name: Pre-Flight Checks for Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate GPL-3.0 License
        uses: datreeio/validate-license-action@v1.0.0
        with:
          args: GPL-3.0

  validate:
    name: Code Validation
    needs: pre-flight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Validate actual code
        run: mvn -B validate --file pom.xml

  compile:
    name: Code Compilation
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cleans and Compile the code
        run: mvn -B clean compile --file pom.xml

  static-code-check:
    name: Static code analysis
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Static code check with checkstyle
        run: mvn -B checkstyle:checkstyle --file pom.xml